# Generated by Django 5.0.4 on 2024-12-03 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='inscription',
            constraint=models.UniqueConstraint(fields=('pensionnaire', 'classe'), name='unique_pensionnaire_classe'),
        ),
    ]
