# Generated by Django 5.1.2 on 2024-10-25 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='roles',
            field=models.CharField(choices=[('ADMIN', 'Administrateur'), ('GESTIONNAIRE', 'Gestionnaire'), ('UTILISATEUR', 'Utilisateur')], default='UTILISATEUR', max_length=20),
        ),
    ]
