# Generated by Django 4.2.13 on 2024-12-30 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0002_parametre'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametre',
            name='is_afficher',
            field=models.BooleanField(default=True),
        ),
    ]
