# Generated by Django 5.0.4 on 2024-12-08 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0002_consultationmedicale_annee_scolaire_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='email',
        ),
    ]
