# Generated by Django 5.1.2 on 2024-11-15 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0003_pensionnnaire_poids_taille_parrain_mere_enfant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='repondant',
            name='revenu_mensuel',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
