# Generated by Django 4.2.13 on 2024-12-30 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0003_parametre_is_afficher'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametre',
            name='blocage_global',
            field=models.BooleanField(default=False, verbose_name="Bloquer l'application"),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='roles',
            field=models.CharField(default='EDUCATIF', max_length=20),
        ),
    ]
