# Generated by Django 5.0.4 on 2024-12-09 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0003_remove_utilisateur_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='dark_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='roles',
            field=models.CharField(default='Utilisateur', max_length=20),
        ),
    ]
