# Generated by Django 5.1.2 on 2024-11-15 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0004_repondant_revenu_mensuel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pensionnnaire',
            name='matricule',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
