# Generated by Django 5.0.4 on 2024-12-10 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0004_alter_utilisateur_dark_mode_alter_utilisateur_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
    ]
