# Generated by Django 5.0.4 on 2024-12-10 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0005_utilisateur_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Numéro de téléphone'),
        ),
    ]
