# Generated by Django 5.0.4 on 2024-12-04 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0005_alter_evaluation_statut_final'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='dark_mode',
            field=models.BooleanField(default=True),
        ),
    ]
