# Generated by Django 5.1.2 on 2024-11-18 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0006_rename_date_naissance_pensionnnaire_date_naissance_enfant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='date_consultation',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='mere_enfant',
            name='date_naissance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parrain',
            name='date_naissance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parrain',
            name='date_parrainage',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pensionnnaire',
            name='date_naissance_enfant',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='pensionnnaire',
            name='date_ouverture_dossier',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='pere_enfant',
            name='date_naissance_pere',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='repondant',
            name='date_naissance',
            field=models.DateField(blank=True, null=True),
        ),
    ]
