# Generated by Django 5.0.4 on 2024-12-05 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0006_utilisateur_dark_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suivi_medicale',
            name='poid',
        ),
        migrations.RemoveField(
            model_name='suivi_medicale',
            name='enfant',
        ),
        migrations.RemoveField(
            model_name='suivi_medicale',
            name='taille',
        ),
        migrations.CreateModel(
            name='ConsultationMedicale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_consultation', models.DateField()),
                ('motif_consultation', models.TextField(blank=True, null=True)),
                ('diagnostic', models.TextField(blank=True, null=True)),
                ('traitement', models.TextField(blank=True, null=True)),
                ('pensionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations_medicales', to='Model.pensionnnaire')),
            ],
        ),
        migrations.CreateModel(
            name='SuiviMedicalTrimestriel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trimestre', models.PositiveSmallIntegerField()),
                ('annee', models.PositiveIntegerField()),
                ('taille_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('poids_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('pensionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suivis_medicaux', to='Model.pensionnnaire')),
            ],
        ),
        migrations.DeleteModel(
            name='Consultation',
        ),
        migrations.DeleteModel(
            name='Poids',
        ),
        migrations.DeleteModel(
            name='Suivi_medicale',
        ),
        migrations.DeleteModel(
            name='Taille',
        ),
        migrations.AddConstraint(
            model_name='suivimedicaltrimestriel',
            constraint=models.CheckConstraint(check=models.Q(('trimestre__in', [1, 2, 3])), name='valid_trimestre_values'),
        ),
        migrations.AlterUniqueTogether(
            name='suivimedicaltrimestriel',
            unique_together={('pensionnaire', 'trimestre', 'annee')},
        ),
    ]
