# Generated by Django 5.1.2 on 2024-11-18 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0007_alter_consultation_date_consultation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pensionnnaire',
            name='statue',
            field=models.CharField(blank=True, choices=[('OP', 'orphelin de pere'), ('OM', 'orphelin de mere'), ('OC', 'orphelin complet'), ('CS', 'cas sociaux'), ('P', 'poupon')], max_length=40, null=True),
        ),
    ]
