# Generated by Django 5.1.2 on 2024-11-18 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0008_alter_pensionnnaire_statue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pensionnnaire',
            name='niveau_etude_anterieur',
            field=models.CharField(blank=True, null=True),
        ),
    ]
