# Generated by Django 5.1.2 on 2024-12-16 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0008_alter_utilisateur_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='pensionnnaire',
            name='poids',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Poids (en kg)'),
        ),
        migrations.AddField(
            model_name='pensionnnaire',
            name='taille',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Taille (en cm)'),
        ),
    ]
