# Generated by Django 5.1.2 on 2024-12-16 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0009_pensionnnaire_poids_pensionnnaire_taille'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dossier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='pensionnaires/dossiers/')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('pensionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dossiers', to='Model.pensionnnaire')),
            ],
        ),
    ]
