# Generated by Django 5.1.2 on 2024-11-20 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0009_alter_pensionnnaire_niveau_etude_anterieur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mere_enfant',
            name='antecedent_medical',
        ),
        migrations.AddField(
            model_name='pensionnnaire',
            name='a_antecdents',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pere_enfant',
            name='situation_matrimoniale_pere',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pere_enfant',
            name='type_habitat_pere',
            field=models.CharField(blank=True, null=True),
        ),
    ]
