# Generated by Django 5.1.2 on 2024-11-20 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0010_remove_mere_enfant_antecedent_medical_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pensionnnaire',
            name='classe_inscrit',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pensionnnaire',
            name='statue',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
