# Generated by Django 5.1.2 on 2024-12-16 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0010_dossier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antecedents',
            name='designation',
            field=models.CharField(),
        ),
    ]
