# Generated by Django 5.1.2 on 2024-11-20 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0011_alter_pensionnnaire_classe_inscrit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mere_enfant',
            name='enfant',
        ),
        migrations.RemoveField(
            model_name='pere_enfant',
            name='enfant',
        ),
        migrations.AddField(
            model_name='pensionnnaire',
            name='mere',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pensionnaires_mere', to='Model.pere_enfant'),
        ),
        migrations.AddField(
            model_name='pensionnnaire',
            name='pere',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pensionnaires_pere', to='Model.pere_enfant'),
        ),
    ]
