# Generated by Django 5.1.2 on 2024-12-16 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0011_alter_antecedents_designation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antecedents',
            name='designation',
            field=models.CharField(blank=True, null=True),
        ),
    ]
