# Generated by Django 5.0.4 on 2024-12-17 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0012_alter_antecedents_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscription',
            name='ecole',
            field=models.CharField(blank=True, null=True),
        ),
    ]
