# Generated by Django 5.1.2 on 2024-11-20 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0012_remove_mere_enfant_enfant_remove_pere_enfant_enfant_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repondant',
            name='enfant',
        ),
        migrations.AddField(
            model_name='pensionnnaire',
            name='combustible',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pensionnnaire',
            name='electrifie_enfant',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='pensionnnaire',
            name='lieu_habitation_enfant',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pensionnnaire',
            name='materiel_revetement',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pensionnnaire',
            name='motif_deplacement_enfant',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pensionnnaire',
            name='nombre_piece_logement',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pensionnnaire',
            name='personne_loge_enfant',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pensionnnaire',
            name='repondant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pensionnaires_repondant', to='Model.repondant'),
        ),
        migrations.AddField(
            model_name='pensionnnaire',
            name='type_eau_enfant',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pensionnnaire',
            name='type_habitat_enfant',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mere_enfant',
            name='situation_matrimoniale',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mere_enfant',
            name='type_habitat',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parrain',
            name='lien_parente',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parrain',
            name='niveau_etude',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parrain',
            name='situation_matrimoniale',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parrain',
            name='type_habitat',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='repondant',
            name='lien_parente',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='repondant',
            name='niveau_etude',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='repondant',
            name='situation_matrimoniale',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='repondant',
            name='type_habitat',
            field=models.CharField(blank=True, null=True),
        ),
    ]
