# Generated by Django 5.1.2 on 2024-11-20 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0013_remove_repondant_enfant_pensionnnaire_combustible_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pensionnnaire',
            name='mere',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pensionnaires_mere', to='Model.mere_enfant'),
        ),
    ]
