# Generated by Django 5.0.4 on 2024-12-17 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0013_inscription_ecole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='ecole',
            field=models.CharField(blank=True, default='OGB', null=True),
        ),
    ]
