# Generated by Django 5.1.2 on 2024-11-21 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0014_alter_pensionnnaire_mere'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mere_enfant',
            name='charge_fixe',
        ),
        migrations.RemoveField(
            model_name='mere_enfant',
            name='electrifie',
        ),
        migrations.RemoveField(
            model_name='mere_enfant',
            name='nombre_piece',
        ),
        migrations.RemoveField(
            model_name='mere_enfant',
            name='situation_matrimoniale',
        ),
        migrations.RemoveField(
            model_name='mere_enfant',
            name='type_eau',
        ),
        migrations.RemoveField(
            model_name='mere_enfant',
            name='type_famille',
        ),
        migrations.RemoveField(
            model_name='mere_enfant',
            name='type_habitat',
        ),
        migrations.RemoveField(
            model_name='pensionnnaire',
            name='combustible',
        ),
        migrations.RemoveField(
            model_name='pensionnnaire',
            name='materiel_revetement',
        ),
        migrations.RemoveField(
            model_name='pensionnnaire',
            name='type_eau_enfant',
        ),
        migrations.RemoveField(
            model_name='pere_enfant',
            name='charge_fixe_pere',
        ),
        migrations.RemoveField(
            model_name='pere_enfant',
            name='electrifie_pere',
        ),
        migrations.RemoveField(
            model_name='pere_enfant',
            name='nationalite_pere',
        ),
        migrations.RemoveField(
            model_name='pere_enfant',
            name='nombre_piece_pere',
        ),
        migrations.RemoveField(
            model_name='pere_enfant',
            name='situation_matrimoniale_pere',
        ),
        migrations.RemoveField(
            model_name='pere_enfant',
            name='type_eau_pere',
        ),
        migrations.RemoveField(
            model_name='pere_enfant',
            name='type_famille_pere',
        ),
        migrations.RemoveField(
            model_name='pere_enfant',
            name='type_habitat_pere',
        ),
        migrations.RemoveField(
            model_name='repondant',
            name='charge_fixe',
        ),
        migrations.RemoveField(
            model_name='repondant',
            name='date_naissance',
        ),
        migrations.RemoveField(
            model_name='repondant',
            name='en_vie',
        ),
        migrations.RemoveField(
            model_name='repondant',
            name='lieu_naissance',
        ),
        migrations.RemoveField(
            model_name='repondant',
            name='niveau_etude',
        ),
        migrations.RemoveField(
            model_name='repondant',
            name='nombre_personne_charge',
        ),
        migrations.RemoveField(
            model_name='repondant',
            name='situation_matrimoniale',
        ),
        migrations.RemoveField(
            model_name='repondant',
            name='type_famille',
        ),
    ]
