# Generated by Django 5.1.2 on 2024-11-21 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0015_remove_mere_enfant_charge_fixe_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mere_enfant',
            name='nationalite',
        ),
    ]
